pass an empty Tags when loading user config (#4)
before this change, if user's `conf.py` references `tags`, it would
fail like

```
poetry run sphinx-multiversion . _build/dirhtml -D html_theme_options.collapse_navigation='false' -D html_theme_options.navigation_depth=3
Traceback (most recent call last):
  File "/home/kefu/.cache/pypoetry/virtualenvs/scylla-1fWQLpOv-py3.9/bin/sphinx-multiversion", line 8, in <module>
    sys.exit(main())
  File "/home/kefu/.cache/pypoetry/virtualenvs/scylla-1fWQLpOv-py3.9/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 214, in main
    config = load_sphinx_config(
  File "/home/kefu/.cache/pypoetry/virtualenvs/scylla-1fWQLpOv-py3.9/lib/python3.9/site-packages/sphinx_multiversion/main.py", line 93, in load_sphinx_config
    raise result
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/kefu/.cache/pypoetry/virtualenvs/scylla-1fWQLpOv-py3.9/lib/python3.9/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/kefu/dev/scylladb/docs/conf.py", line 69, in <module>
    tags.add(flag)
AttributeError: 'NoneType' object has no attribute 'add'
```

because tags is `None` by default, see
https://www.sphinx-doc.org/en/master/_modules/sphinx/config.html
for the definition of `Config.read()` method.

after this change, an empty `Tags` is used when loading user's
configuration. so it is able to add the customized tags to the
`Tags` instance. this should fix the build failure of sphinx
projects using `tags` and sphinx_multiversion.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>